# Generated by Django 5.1.6 on 2025-02-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confident", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pdfdocument",
            table="confident_pdfdocument",
        ),
    ]
