# Generated by Django 5.1.6 on 2025-02-24 21:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stp_raster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("year", models.IntegerField(help_text="Year of the raster data")),
                (
                    "rast",
                    django.contrib.gis.db.models.fields.RasterField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution in map units",
                        null=True,
                    ),
                ),
                ("times", models.CharField(default=None, max_length=10)),
            ],
            options={
                "ordering": ["year"],
                "indexes": [
                    models.Index(fields=["year"], name="visuall_stp_year_bea69f_idx")
                ],
            },
        ),
    ]
