# Generated by Django 5.1.6 on 2025-02-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visuall", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stp_raster",
            new_name="raster_visual",
        ),
        migrations.RenameIndex(
            model_name="raster_visual",
            new_name="visuall_ras_year_153920_idx",
            old_name="visuall_stp_year_bea69f_idx",
        ),
    ]
