# Generated by Django 5.1.6 on 2025-02-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visuall", "0002_rename_stp_raster_raster_visual_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raster_visual",
            old_name="times",
            new_name="phase",
        ),
    ]
