# Generated by Django 5.1.6 on 2025-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuall", "0003_rename_times_raster_visual_phase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raster_visual",
            options={"ordering": ["year_phase"]},
        ),
        migrations.RemoveIndex(
            model_name="raster_visual",
            name="visuall_ras_year_153920_idx",
        ),
        migrations.RemoveField(
            model_name="raster_visual",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="raster_visual",
            name="year",
        ),
        migrations.AddField(
            model_name="raster_visual",
            name="year_phase",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddIndex(
            model_name="raster_visual",
            index=models.Index(
                fields=["year_phase"], name="visuall_ras_year_ph_73f259_idx"
            ),
        ),
    ]
