# Generated by Django 5.1.6 on 2025-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuall", "0004_alter_raster_visual_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raster_visual",
            name="year_phase",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
