# Generated by Django 5.1.6 on 2025-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuall", "0005_alter_raster_visual_year_phase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raster_visual",
            options={"ordering": ["phase_year"]},
        ),
        migrations.RemoveIndex(
            model_name="raster_visual",
            name="visuall_ras_year_ph_73f259_idx",
        ),
        migrations.RenameField(
            model_name="raster_visual",
            old_name="year_phase",
            new_name="phase_year",
        ),
        migrations.AddIndex(
            model_name="raster_visual",
            index=models.Index(
                fields=["phase_year"], name="visuall_ras_phase_y_db93ff_idx"
            ),
        ),
    ]
